### PR TITLE
[composer] Add provide key

### PR DESCRIPTION
**Pull request by Maks3w**
For packages aliasing the original fork like fr3d/xmldsig

### CODE REVIEW

**Comment by relaxnow** [comment]
:+1: seems good to me, @jaimeperez ?

**Comment by jaimeperez** [comment]
Not sure, actually. I'd still like to keep this repo in sync with Rob Richards' master (besides the branch I created with the c14n fix that's still pending his review). Even though this is something not affecting the library itself, it breaks the one to one relationship between master here and trunk in Google Code. To make things worse, it would enable people to start using this repo, which is something I'm not sure we want...

**Comment by Maks3w** [comment]
By steps

- The repo is already unsynced due the existence of composer package definition file. 

- The proposal already improve not use an explicit package depency by 3rd party libraries 

- I'm in the same use case like you. I've a fork for just host a patch. On xmldsig repo I encourage the user to manual add the upstream source in his own Composer's root package

**Comment by Maks3w** [comment]
I wrote to @robrichards if he want help for manage the project but I do not receive any response.

Do you want to collaborate in a common fork where centralize community patches?

**Comment by jaimeperez** [comment]
Hi @Maks3w!

Sorry for the late response. You are right with regard to our repo being already out of sync. However, it is out of sync just because of the composer package, so essentially the library is the same, which is what I meant.

The main reason why I don't want to start providing `cdatazone/xmlseclibs` is that I don't want people to start using this repository. I created this fork just for our own personal use in SimpleSAMLphp, but if people starts to use this fork then we'll have all of a sudden bigger responsibilities over it.

On the other hand, we are now having the (somewhat recurring) discussion about forking *xmlseclibs* and maintaining it ourselves. I would say the minimum requirement for that to happen is having someone with superb knowledge of XML and xmldsig, which is not my case, unfortunately.

**Comment by Maks3w** [comment]
I think we can together to provide some kind of coordination around the community forks until a volunteer wants to lead the project.

For to coordinate bugfixes I think we can do it with our limit knowledge. For to me not have sense to have a fork with a small patch for bug X and another fork with a patch for bug Y.

I would like join efforts together. If you want we could continue the conversation by IRC (irc.freenode.net @maks3w) or email (github.maks3w at virtualplanets.net). I guess you speak spanish, me too

**Comment by robrichards** [comment]
Outside of the C14N change, do you have other changes that aren't yet 
included in my repo?

Rob

**Comment by Maks3w** [comment]
Hi @robrichards 

In my fork there is this patch https://github.com/Maks3w/xmlseclibs/commit/cb6ef914c79a3afc71a58baabb5ad7cd7661e25e

Related to https://github.com/robrichards/xmlseclibs/issues/17

Also there is a need from all PHP community of to publish the project in packagist.org (Composer)

Additionally there are 17 forks (https://github.com/search?utf8=%E2%9C%93&q=xmlseclibs) many of   with patches (https://github.com/Maks3w/xmlseclibs/network)


Actually the project need to do 3 things:

1) Merge forks in your repository.

2) Update the project with actual OSS structures (Continuous-Integration, PHP namespaces, Composer package, ...)

3) Call to authors of the ported issues and respond to the questions/bugfix


I already wrote you a few weeks ago offering my time for to help you with the project. My offer is still valid :)

**Comment by robrichards** [comment]
Would appreciate the help. I currently working through the patches that 
have been submitted. So far I have added the C14N speed issue - with 
some modifications as to not break other use cases. Am looking at your 
patch now. Can you also send me a patch for adding composer support?

Once I can get a solid base established, i.e. just recently got it 
migrated to github, will then start looking into centralizing the forks 
out there.

Rob

**Comment by Maks3w** [comment]
@robrichards Do you know the GitHub flow?

Sure you know but I will reminder it. In GitHub people forks the upstream repository in his personal account, then the user changes the code. Finally GitHub provide a feature for send the patch directly to the upstream.

This feature is the [Pull request](https://help.github.com/articles/using-pull-requests/), the developer directly open an issue in your project asking you to merge the patch.

Then the maintainer can review the code in his/her web browser and if agree press the Merge button and automatically the patch is merged in the upstream code.

See https://help.github.com/articles/using-pull-requests/ for more details about this agile way of collaborate.

**Comment by Maks3w** [comment]
@robrichards PR for composer https://github.com/robrichards/xmlseclibs/pull/33

**Pull request closed without merging**
